trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
steps:
- task: UseDotNet@2
  displayName: 'Use .Net Core sdk 3.0.100-preview7-012821'
  inputs:
    version: '3.0.100-preview7-012821'

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(Parameters.RestoreBuildProjects)'

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
    packagesToPack: '*/Hetacode.*/*.csproj'
    versioningScheme: byBuildNumber

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: push
    publishVstsFeed: '52a7c98e-8d7f-4bdf-b79f-8f96e7bd8012'
