trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.0.100-preview7-012821'
    includePreviewVersions: true
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '*/Hetacode.*/*.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '*/Hetacode.*/*.csproj'
    versioningScheme: 'byBuildNumber'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false

# - task: DotNetCoreCLI@2
#   displayName: Publish
#   inputs:
#     command: push
#     publishVstsFeed: '52a7c98e-8d7f-4bdf-b79f-8f96e7bd8012'
